export * from './dashboard/Dashboard'
export * from './pessoas/ListagemDePessoas'
export * from './pessoas/DetalhePessoas'
export * from './cidades/ListagemDeCidades'
export * from './cidades/DetalheCidades'